version: '3.4'

services:
  infrateam:
    image: infrateam
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
      - 4000:4000
    environment: 
      ApiAddress: http://127.0.0.1:4000/WeatherForecast