version: '3.4'

services:
  infrateam:
    image: infrateam
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:5000
    environment: 
      ApiAddress: http://infra-team-test-infrateam-1:5000/WeatherForecast